name: Prune Older Workflow Runs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_SECRET: ${{ secrets.GITHUB_SECRET }}

jobs:
  prune-workflow-runs:
    name: Prune Older Workflow Runs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install GitHub CLI
        run: npm install -g gh@2

      - name: Authenticate with GitHub CLI
        run: gh auth login --with-token ${{ secrets.GITHUB_SECRET }}

      - name: Prune Runs
        run: |
          gh pr list -L 5 --json number,state,base.repo.full_name -q "is:merged base:${{ github.ref }}" |
          jq -r ".[].number" |
          xargs -I {} gh pr close {}
