name: Prune Older Workflow Runs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  prune-workflow-runs:
    name: Prune Older Workflow Runs
    runs-on: ubuntu-latest
    steps:
      - name: Setup GitHub Script
        uses: actions/github-script@v4
        with:
          script: npm install @actions/github@v5

      - name: Prune Runs
        uses: actions/github-script@v4
        with:
          script: |
            const repo = context.repo;
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            
            const workflows = await octokit.actions.listRepoWorkflows({
              ...repo,
              per_page: 100 // Increase the per_page value if needed
            });
            
            for (const workflow of workflows.data.workflows) {
              console.log(`Listing runs for workflow: ${workflow.name}`);
              const runs = await octokit.actions.listWorkflowRuns({
                ...repo,
                workflow_id: workflow.id,
                status: 'completed',
                per_page: 100 // Increase the per_page value if needed
              });
              
              if (runs.data.total_count > 5) {
                const runsToDelete = runs.data.workflow_runs.slice(5).map(run => run.id);
                for (const runId of runsToDelete) {
                  console.log(`Deleting run: ${runId}`);
                  await octokit.actions.deleteWorkflowRun({
                    ...repo,
                    run_id: runId
                  });
                }
              }
            }
