name: Prune Older Workflow Runs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_SECRET: ${{ secrets.GITHUB_SECRET }}

jobs:
  prune-workflow-runs:
    name: Prune Older Workflow Runs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Authenticate with GitHub CLI
        run: |
          unset GITHUB_TOKEN
          echo "${{ secrets.GITHUB_SECRET }}" > gh_token
          gh auth login --with-token < gh_token

      - name: Prune Runs
        run: |
          gh pr list --limit 5 --state merged |
          jq -r ".[].number" |
          xargs -I {} gh pr close {}
