name: Prune Workflows

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  prune-workflows:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate with GitHub Token
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Workflow Runs
        id: get-runs
        run: |
          echo "::set-output name=runs::$(gh workflow run list --json id,status | jq -r '.[] | select(.status != "in_progress") | .id')"

      - name: Sort Workflow Runs
        id: sort-runs
        run: |
          echo "::set-output name=sorted_runs::$(echo '${{ steps.get-runs.outputs.runs }}' | tr ' ' '\n' | sort -r | tr '\n' ' ')"

      - name: Prune Old Workflow Runs
        run: |
          IFS=$'\n'
          runs=(${{ steps.sort-runs.outputs.sorted_runs }})
          keep_count=5
          for ((i=keep_count; i<${#runs[@]}; i++)); do
            run_id=${runs[i]}
            echo "Deleting run ID: $run_id"
            gh workflow run delete "$run_id" --force
          done
